### ISSUE TITLE
Installation fails on Logstash 5.x

### ISSUE THREAD

**Issue by michelechersich** [FujitsuEnablingSoftwareTechnologyGmbH/logstash-output-monasca_log_api#3]
Hello,
I'm having problems in building a Docker container with Logstash 5.x and the logstash-output-monasca_log_api plugin version 0.5.3.

The plugin installation fails as shown below:

`Building monasca-log-agent
Step 1/4 : FROM logstash:5
---> 413f93f5f1f2
Step 2/4 : RUN logstash-plugin install logstash-output-monasca_log_api
---> Running in 21f002491274
Validating logstash-output-monasca_log_api
Installing logstash-output-monasca_log_api
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-codec-json":
In snapshot (Gemfile.lock):
logstash-codec-json (= 3.0.2)

In Gemfile:
logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java

logstash-output-monasca_log_api (>= 0) java depends on
logstash-codec-json (~> 0.1.6) java

logstash-output-udp (>= 0) java depends on
logstash-codec-json (>= 0) java
Running bundle update will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`

The problem seems to be that Logstash 5.x locks the logstash-codec-json plugin version to 3.0.2, whereas the logstash-output-monasca_log_api plugin depends on a previous version.

I reported the same problem on the Docker Logstash image repository: https://github.com/elastic/logstash-docker/issues/17

Their suggestion is to update the plugin and its dependencies for Logstash 5.x.

**Comment by kejc87** [comment]
Hello,

currently we are using logstash 2.3.4. I know there is an information in the readme that you could use logstash >= 2.2.0, but we haven't tested logstash 5.0 compatibility yet.

Regards

**Comment by michelechersich** [comment]
Thanks for your answer. I'm now trying Logstash 2.3.4 and the installation succeeds.

Now, I have the following run time error:
`{:timestamp=>"2017-03-06T13:56:53.250000+0000", :message=>"Pipeline aborted due to error", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-monasca_log_api-0.5.3/lib/logstash/outputs/keystone/token.rb:30:in `request_new_token'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-monasca_log_api-0.5.3/lib/logstash/outputs/monasca_log_api.rb:167:in `check_token'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-monasca_log_api-0.5.3/lib/logstash/outputs/monasca_log_api.rb:94:in `init_token'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-monasca_log_api-0.5.3/lib/logstash/outputs/monasca_log_api.rb:73:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473:in `start_pipeline'"], :level=>:error}
{:timestamp=>"2017-03-06T13:56:56.260000+0000", :message=>"stopping pipeline", :id=>"main"}`

Here is also my logstash.conf:
`input {
  file {
    add_field => { "dimensions" => { "service" => "system" }}
    path => "/var/log/sample.log"
    tags => ["syslog"]
  }
}

filter {
  if "syslog" in [tags] {
    multiline {
      negate => "true"
      pattern => "^%{SYSLOGTIMESTAMP}"
      what => "previous"
    }
  }
}

output {
  monasca_log_api {
    monasca_log_api_url => "http://monasca-log-api:8090"
    keystone_api_url => "http://keystone:35357"
    project_name => "mini-mon"
    username => "monasca-agent"
    password => "password"
    user_domain_name => "default"
    project_domain_name => "default"
    dimensions => [ "hostname:monasca-log" ]
  }
}`

Thanks

**Comment by kornicameister** [comment]
Maybe it's worth mentioning that monasca community (sorry I don't recall who exactly) has plans on adding ELK5.
