### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by michelechersich** [FujitsuEnablingSoftwareTechnologyGmbH/logstash-output-monasca_log_api#4]
Hello,
running the plugin with Logstash 2.3.4 I get the following runtime error:

`{:timestamp=>"2017-03-06T13:56:53.250000+0000", :message=>"Pipeline aborted due to error", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-monasca_log_api-0.5.3/lib/logstash/outputs/keystone/token.rb:30:in `request_new_token'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-monasca_log_api-0.5.3/lib/logstash/outputs/monasca_log_api.rb:167:in `check_token'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-monasca_log_api-0.5.3/lib/logstash/outputs/monasca_log_api.rb:94:in `init_token'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-monasca_log_api-0.5.3/lib/logstash/outputs/monasca_log_api.rb:73:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473:in `start_pipeline'"], :level=>:error}
{:timestamp=>"2017-03-06T13:56:56.260000+0000", :message=>"stopping pipeline", :id=>"main"}`

Here is also my logstash.conf:
`input {
  file {
    add_field => { "dimensions" => { "service" => "system" }}
    path => "/var/log/sample.log"
    tags => ["syslog"]
  }
}

filter {
  if "syslog" in [tags] {
    multiline {
      negate => "true"
      pattern => "^%{SYSLOGTIMESTAMP}"
      what => "previous"
    }
  }
}

output {
  monasca_log_api {
    monasca_log_api_url => "http://monasca-log-api:8090"
    keystone_api_url => "http://keystone:35357"
    project_name => "mini-mon"
    username => "monasca-agent"
    password => "password"
    user_domain_name => "default"
    project_domain_name => "default"
    dimensions => [ "hostname:monasca-log" ]
  }
}`

Can you figure out the problem?
Thanks

**Comment by kejc87** [comment]
Hello,

I just checked my current configuration and for me it looks like your url definition in the monasca_log_api output plugin is wrong. That's how my configuration looks like:

```
output {
  monasca_log_api {
    monasca_log_api_url => "http://192.168.10.4:5607/v3.0"
    keystone_api_url => "http://192.168.10.5:35357/v3"
    project_name => "mini-mon"
    username => "monasca-agent"
    password => "password"
    user_domain_name => "default"
    project_domain_name => "default"
    dimensions => ["hostname:monasca", "service:monasca"]
  }
}
```

I think you need to add the v3 and v3.0 path to the keystone_api_url and monasca_log_api_url.

I agree that the current exception message looks weird and should be changed.

**Comment by michelechersich** [comment]
That did it. Thanks a lot!
